<?php require_once 'layout/header.phtml'; ?>

<div class="">
    <form action="<?= BASE_URL ?>nueva" method="POST" class="form-producto">
        <h2>Agregar Nuevo Producto</h2>

        <div class="form-group">
            <label for="name">Nombreee:</label>
            <input type="text" name="name" id="name" required>
        </div>

        <div class="form-group">
            <label for="img">URL de Imagen:</label>
            <input type="url" name="img" id="img" required>
        </div>

        <div class="form-group">
            <label for="model">Modelo:</label>
            <input type="text" name="model" id="model" required>
        </div>

        <div class="form-group">
            <label for="price">Precio:</label>
            <input type="number" name="price" id="price" required>
        </div>

        <div class="form-group">
            <label for="description">Descripción:</label>
            <textarea name="description" id="description" required></textarea>
        </div>

        <div class="form-group">
            
            <label for="id_category">Categoría:</label>
            <select name="id_category" id="id_category" required>

                <option value="1">iPhone / iPad / Mac</option>
                <option value="2">Apple Watch</option>
                <option value="3">AirPods</option>
                <option value="4">HomePod / Apple TV</option>
                <option value="5">Accesorios</option>
            </select>
        </div>

        <button type="submit">Agregar Producto</button>
    </form>
</div>
<?php require_once './templates/form.add.category.phtml'; ?>
<?php require_once 'products.phtml'; ?>
<?php require_once 'layout/footer.phtml'; ?>