<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="css/style.css">
    <title>Tienda digital</title>
</head>
<body>
  <header class="main-header">
    <h1>Tienda digital</h1>
    <nav class="nav-bar">
        <ul class="nav-list">
                        
            <?php if (isset($_SESSION['USER_ID'])) { ?>
            <li><a href="<?= BASE_URL ?>categorias">Categorias</a></li>
            <li><a href="<?= BASE_URL ?>producto-nuevo">Productos</a></li>
            
            <li><a href="<?= BASE_URL ?>logout">Cerrar Sesión</a></li> 
        <?php } else { ?>
            <li><a href="<?= BASE_URL ?>home">Home</a></li>
            <li><a href="<?= BASE_URL ?>login">Iniciar Sesión</a></li>
        <?php } ?>
        </ul>
    </nav>
</header>
