<?php require_once 'layout/header.phtml'; 
      require_once './templates/form.add.category.phtml';
    ?>

<main class="content-wrapper">
    
    <div class="category-grid-container"> 
        
        <?php foreach ($categories as $category) { ?>
            
            <article class="category-card">
                
                <a href="<?= BASE_URL ?>categoria/<?= $category->id ?>" class="card-link">

                    <h3 class="category-card__name"><?= $category->name ?></h3>
                    
                    <img src="<?= $category->img ?>" alt="<?= $category->name ?>" class="category-card__image">
                    
                    <p class="category-card__description"><?= $category->description ?></p>
                    
                   
                    
                </a>

                <div class="category-card__actions">
                    <a href="<?= BASE_URL ?>eliminar-categoria/<?= $category->id ?>" class='btn btn-danger btn-sm' 
                       onclick="return confirm('¿Seguro que quieres eliminar esta categoría?');">Eliminar</a> 
                    <a class="btn btn-warning btn-sm" href="<?= BASE_URL ?>editar-categoria/<?= $category->id ?>">Editar</a> 
                </div>

            </article>
        
        <?php } ?>
    </div>
    
</main>

<?php require_once 'layout/footer.phtml'; ?>