<?php require_once 'layout/header.phtml'; ?>

<div class="">
    <form action="<?= BASE_URL ?>categorias" method="POST" class="">
        <h2>Agregar Nueva Categoría</h2>

        <div class="form-group">
            <label for="name">Nombre:</label>
            <input type="text" name="name" id="name" required>
        </div>

        <div class="form-group">
            <label for="img">URL de Imagen:</label>
            <input type="url" name="img" id="img" required>
        </div>

        <div class="form-group">
            <label for="description">Descripción:</label>
            <textarea name="description" id="description" required></textarea>
        </div>

        
        <button type="submit">Agregar Categoría</button>
    </form>
</div>

<?php require_once 'layout/footer.phtml'; ?>