<?php require_once 'layout/header.phtml'; 
?>

<div class="login-page">
    <form action="do_login" method="POST" class="login-form">
        <h2>Iniciar Sesión</h2>
        <label for="user">Usuario:</label>
        <input type="text" name="user" id="user" placeholder="Usuario">

        <label for="password">Contraseña:</label>
        <input type="password" name="password" id="password" placeholder="Contraseña">

        <button type="submit">Iniciar Sesión</button>
    </form>
</div>
