<?php require_once 'layout/header.phtml'; ?>

<main class="content-wrapper">

    <section class="welcome-container">
        <div class="welcome-text">
            <h1>La mejor forma de comprar tus productos favoritos.</h1>
            <p>Descubrí los últimos productos de Apple, desde iPhones hasta accesorios exclusivos.</p>
            <a href="#form-filtro" class="btn-shop">Ir a Productos</a>
        </div>
        <div class="welcome-image">
            <img src="https://www.apple.com/la/iphone-17-pro/images/overview/highlights/highlights_design_endframe__flnga0hibmeu_large.jpg" alt="Banner Apple">
        </div>
    </section>

    <section class="promo-container">
        <h2>Productos Destacados</h2>
        <p>Los productos más recientes y populares del catálogo. En valor dolar</p>
    </section>

    
    <?php require_once './templates/form.filtro.phtml'; ?>
    <?php require_once './templates/products.phtml'; ?>

</main>

<?php require_once 'layout/footer.phtml'; ?>
