<?php
require_once 'layout/header.phtml';
?>
<div  class="products-grid-container">
    <?php foreach ($products as $product) { ?>

        <article class="product-card">

            <a href="<?= BASE_URL ?>producto/<?= $product->id ?>" class="card-link">

                <h3 class="product-card__name"><?= $product->name ?></h3>

                <img src="<?= $product->img ?>" alt="<?= $product->name ?>" class="product-card__image">

                <div class="product-card__info-group">
                    <p class="product-card__info">Modelo: <span><?= $product->model ?></span></p>
                    <p class="product-card__info product-card__price">Precio: $<?= $product->price ?></p>
                    <p class="product-card__description"><?= $product->description ?></p>
                    <p class="product-card__category">Categoría: <span><?= $product->category_name ?></span></p>
                </div>
            </a>
            

            <?php if (isset($_SESSION['USER_ID'])) { ?>
                <div class="product-card__actions">
                    <a href="<?= BASE_URL ?>eliminar-producto/<?= $product->id ?>" class='btn btn-danger btn-sm'
                        >Eliminar</a>
                    <a class="btn btn-warning btn-sm" href="<?= BASE_URL ?>editar-producto/<?= $product->id ?>">Editar</a>
                </div>
            <?php } ?>
        </article>

    <?php } ?>
</div>


