<?php require_once 'layout/header.phtml'; 
      require_once 'layout/main.phtml';
      require_once './templates/form.filtro.phtml';
?>

<form method="GET" class="filter-form">
    <label for="category">Categorías </label>
    <select name="category" id="category" onchange="this.form.submit()">

        <option value="">Todas</option>
        <?php foreach ($categories as $category) { ?>

            <option value="<?= $category->id ?>">
                <?= $category->name ?>
                

                <?= (isset($_GET['category']) && $_GET['category'] == $category->id) ? 'selected' : '' ?>>
                <?= $category->name ?>
            </option>
        <?php } ?>
    </select>
</form>


<div class="products-container">
    <?php
    // Guardamos el valor seleccionado (o vacío si no hay selección)
    $selectedCategory = $_GET['category'] ?? '';        


    <?php foreach ($products as $product) { ?>
        <? if ($selectedCategory === '' || $product->category_id == $selectedCategory){ ?>
        <div class="product-card">
            <div id="product-name" class= "product-info"><?= $product->name ?></div>
            
            <img src="<?= $product->img ?>" alt="<?= $product->name ?>" class="product-image">
            <div class="product-info">Modelo: <?= $product->model ?></div>
            <div class="product-info">Precio: $<?= $product->price ?></div>
            <div class="product-info"><?= $product->description ?></div>
            <div class="product-info">Categoría: <?= $product->category_name ?></div>
        </div>
        <?php } ?>
    <?php } ?>
</div>

<?php require_once 'layout/footer.phtml'; ?>

