</main> 

<footer class="main-footer">
    <div class="footer-content">
        
        <ul class="footer-nav">
            <li>Contacto</a></li> 
            <li>Nuestras Tiendas</a></li> 
            <li>Preguntas frecuentes</a></li>
            <li>Administración</a></li>
        </ul>

        <p class="footer-copyright">
            © 2025 Tienda Digital Cheves & D'Annunzio. Todos los derechos reservados.
        </p>
        
    </div>
</footer>

</body>
</html>